### ISSUE TITLE
add rewards capture column where applicable

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/influence-toolkit#2]
mostly referring to bunni here due to velit holders capturing relatively more rewards

**Comment by petrovska-petro** [comment]
did a gsheet to have an idea of what calcs we will need to carry: https://docs.google.com/spreadsheets/d/15wWH81Cd43-mJrH1_nAMuVdfZctW64SZqWBm2IoG6I4/edit#gid=0
